services:
    portfolio:
        container_name: portfolio
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/portfolio
        env_file:
            - ../.env
        restart: always
        networks:
            - reverse_proxy
networks:
    reverse_proxy:
        external: true
