const config = {
    DATABASE_URL: process.env.DATABASE_URL!,
    GITHUB_ACCESS_TOKEN: process.env.GITHUB_ACCESS_TOKEN!,
    GITHUB_REPO_OWNER: process.env.GITHUB_REPO_OWNER!,
    IMPORT_PROJECTS_CRON_ACCESS_TOKEN: process.env.IMPORT_PROJECTS_CRON_ACCESS_TOKEN!
}

export default config;