name: import-projects-cron
on:
    schedule:
        - cron: "0 0 * * *"
jobs:
    cron:
        runs-on: ubuntu-latest
        steps:
            - name: hit "import-projects-route" every day
              run: |
                  curl --request POST \
                  --url '${{ vars.API_URL }}${{ vars.IMPORT_PROJECTS_ROUTE }}' \
                  --header 'Authorization: Bearer ${{ secrets.IMPORT_PROJECTS_CRON_ACCESS_TOKEN }}'
