name: import-repos-cron-test
on:
    push:
        branches:
            - "test-workflows"
jobs:
    cron:
        runs-on: ubuntu-latest
        steps:
            - name: hit "import-repos-route"
              run: |
                  curl --request POST \
                  --url '${{ vars.API_URL }}${{ vars.IMPORT_REPOS_ROUTE }}' \
                  --header 'Authorization: Bearer ${{ secrets.IMPORT_REPOS_CRON_ACCESS_TOKEN }}'
