name: import-projects-cron-test
on:
    push:
        branches:
            - "test-workflows"
jobs:
    cron:
        runs-on: ubuntu-latest
        steps:
            - name: get auth token
              run: |
                  username=${{secrets.ADMIN_USERNAME}}
                  echo $username
                  authToken=$(curl --request POST --header 'Content-Type: application/json' --data '{"username": "${{ secrets.ADMIN_USERNAME }}", "password": "${{ secrets.ADMIN_PASSWORD }}"}' --url '${{ vars.API_URL }}/auth/custom-sign-in')
                  echo $authToken
                  curl --request POST \
                  --url '${{ vars.API_URL }}${{ vars.IMPORT_PROJECTS_ROUTE }}' \
                  --header 'auth-token: $authToken'
